### ISSUE TITLE
Unable to run sh script inside packages

### ISSUE THREAD

**Issue by mmunerato** [amazon-science/probconserv#2]
Dear All,

I tried to set up the ProbConserv package without any good result. I have a Ubuntu 22.04 LTS machine with a virtual environment dedicated. The Python version in 3.10.13.
I installed poetry, I created the poetry lock file commenting the line wemake-python-styleguide = "^0.16.1" (otherwise I had a warning concerning the version of python that is compliant with the warning) and then I installed using pip the version of wemake-python-styleguide required.
When I try to run, for example, the 2b_stefan_var_p.sh script this is the output:
`
Traceback (most recent call last):
  File "/home/munerato/PhysicalLearning/probconserv/deep_pdes/experiments/generate.py", line 7, in <module>
    from deep_pdes.datasets.base import ANPDataset
ModuleNotFoundError: No module named 'deep_pdes'
Error executing job with overrides: ['+experiments=2b_stefan_var_p', '+train=2b_stefan_var_p_anp']
Error locating target 'deep_pdes.attentive_neural_process.anp.ANP', see chained exception above.
full_key: methods.anp.model

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Error executing job with overrides: ['+experiments=2b_stefan_var_p', '+train=2b_stefan_var_p_pinp']
Error locating target 'deep_pdes.attentive_neural_process.softc.PINP', see chained exception above.
full_key: methods.pinp.model

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Traceback (most recent call last):
  File "/home/munerato/PhysicalLearning/probconserv/deep_pdes/experiments/analyze.py", line 16, in <module>
    from deep_pdes.attentive_neural_process.anp import ANP
ModuleNotFoundError: No module named 'deep_pdes'
`

Do you have any ideas how to resolve it?

Thanks in advance,
Mauro

**Comment by dereklhansen** [comment]
Did you run "poetry shell" beforehand?

**Comment by mmunerato** [comment]
Dear Derek,
I reinstalled all the package and now it works. I did not understand why previously I followed the same way and does not work. I suppose there was some problem with environments (I created my own an environment with the same packages listed in the toml file).
So sorry for the disturb and thank you so much!
